print('olá, meu mundo')
print('hoje o dia está lindo')
print('estou com saudade do namorado')
print('hoje irei sair com minhas amigas para o mc')
print('mas queria ver meu chuchu, beijinhos, saudade da sua amada')